### PR TITLE
Operator for Trigger Eff Study

### PR DESCRIPTION
**Pull request by MDallOsso**
Lots of warning of different size between the Muon pt and pfIso

### CODE REVIEW

**Comment by pablodecm** [comment]
Warnings are caused because there is a important bug in my previous TTree reading code. I suggest that you incorporate that fix in this PR.

**Comment by pablodecm** [comment]
It is just clearing the pfiso03 vector in the Event::update method, that is,
adding:

```
muons_pfiso03_.clear()
```

after https://github.com/MDallOsso/alp_analysis/blob/master/interface/Event.h#L83

**Comment by MDallOsso** [comment]
now it can be merged.
there is still a warning message from root regarding histos:
TROOT::Append:0: RuntimeWarning: Replacing existing TH1: h_jets_ht (Potential memory leak).

**Comment by pablodecm** [comment]
That is because we have two histograms associated to the same file with the same name. Not a big deal but if you find it fix it.

**Pull request merged**
